// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVEWOl85Q-A9DbtabNWuY-sxrW2ZgHayw',
    appId: '1:138343503394:android:cf7173272a226b1e429c7b',
    messagingSenderId: '138343503394',
    projectId: 'ctracker-d932b',
    authDomain: 'ctracker-d932b.firebaseapp.com',
    storageBucket: 'ctracker-d932b.appspot.com',
    measurementId: 'G-7NY13PYYKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVEWOl85Q-A9DbtabNWuY-sxrW2ZgHayw',
    appId: '1:138343503394:android:8301094b2ba9f754429c7b',
    messagingSenderId: '138343503394',
    projectId: 'ctracker-d932b',
    storageBucket: 'ctracker-d932b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-Pz4lEdGD_5CkolwZsuWxvk5YH0Xy-k',
    appId: '1:1045475764615:ios:25973a1fc7add129f4cb22',
    messagingSenderId: '1045475764615',
    projectId: 'presence-5c341',
    storageBucket: 'ctracker-d932b.appspot.com',
    iosClientId: '1045475764615-sh6bdtfvq5gi9hdi9elu247v7usqsvpl.apps.googleusercontent.com',
    iosBundleId: 'com.mrezys',
  );
}
